name: Forked CI
on:
  workflow_dispatch:
    inputs:
      number:
        description: "Pull Request Number"
        required: true
jobs:
  trigger-chromatic:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Chromatic workflow
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner
              repo: context.repo.repo
              workflow_id: "chromatic.yml"
              ref: "master"
              inputs: {
                "number": "${{ github.event.inputs.number }}"
              }
            })
        env:
          GITHUB_TOKEN: ${{ secrets.CHROMATIC_WORKFLOW_TOKEN }}

  trigger-cypress:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Cypress workflow
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner
              repo: context.repo.repo
              workflow_id: "cypress.yml"
              ref: "master"
              inputs: {
                "number": "${{ github.event.inputs.number }}"
              }
            })
        env:
          GITHUB_TOKEN: ${{ secrets.CYPRESS_WORKFLOW_TOKEN }}

  trigger-playwright:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Playwright workflow
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner
              repo: context.repo.repo
              workflow_id: "playwright.yml"
              ref: "master"
              inputs: {
                "number": "${{ github.event.inputs.number }}"
              }
            })
        env:
          GITHUB_TOKEN: ${{ secrets.PLAYWRIGHT_WORKFLOW_TOKEN }}
